[package]
name = "starview"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
patch = "0.7.0"
rayon = "1.10.0"
similar = "2.7.0"
tempfile = "3.20.0"
thiserror = "2.0.12"
walkdir = "2.5.0"
zip = "4.0.0"
