[package]
name = "starview_patch"
edition = "2024"

[dependencies]
patch.workspace = true
rayon.workspace = true
tempfile.workspace = true
thiserror.workspace = true
walkdir.workspace = true
zip.workspace = true